---
# This playbook deploys a simple standalone Tomcat 7 server.

- hosts: localhost
  connection: local
  become_user: "{{ local_user | default('awx') }}"
  become: yes


  roles:
    - selinux
    - tomcat
